import type { Metadata, Viewport } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';

import { Footer } from '@/components/footer';
import { Header } from '@/components/header';
import { themeInitScript } from '@/components/theme-toggle';
import { SITE } from '@/lib/site';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  display: 'swap',
});

/**
 * The project has no canonical host yet, so the base URL follows mechanically from the
 * repository placeholder in lib/site.ts rather than inventing a domain. Pass
 * NEXT_PUBLIC_SITE_URL at build time to point the absolute URLs at a real deployment.
 */
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://carlcastanas.github.io/forge';

const PAGE_TITLE = `${SITE.name} — ${SITE.tagline}`;

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: PAGE_TITLE,
    template: `%s — ${SITE.name}`,
  },
  description: SITE.description,
  applicationName: SITE.name,
  robots: { index: true, follow: true },
  // app/icon.svg and app/apple-icon.png are generated by assets/brand/generate.mjs.
  icons: {
    icon: [{ url: '/icon.svg', type: 'image/svg+xml' }],
    apple: [{ url: '/apple-icon.png', sizes: '180x180', type: 'image/png' }],
  },
  // The card images come from app/opengraph-image.png and app/twitter-image.png, which
  // Next resolves against metadataBase. Do not repeat them here.
  openGraph: {
    type: 'website',
    siteName: SITE.name,
    title: PAGE_TITLE,
    description: SITE.description,
    url: SITE_URL,
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    title: PAGE_TITLE,
    description: SITE.description,
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="page-shell">
          <a className="skip-link" href="#main">
            Skip to content
          </a>
          <Header />
          <main id="main" className="page-main" tabIndex={-1}>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
